defaults: &defaults
 
:development:
  :couchdb:
    :url: http://localhost:5984/whatsbest_dev
  <<: *defaults
  
:test:
  :couchdb:
    :url: http://localhost:5984/whatsbest_test
    <<: *defaults

:production:
  :couchdb:
    :url: http://localhost:5984/whatsbest_prod
    <<: *defaults